version: '3.8'

services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    network_mode: host  # Allows Samba to broadcast over local network
    environment:
      - USERID=1000  # Adjust to your user ID
      - GROUPID=1000 # Adjust to your group ID
    volumes:
      - /:/mount  # Sharing entire filesystem (be cautious!)
    command: >
      -u "robinmorajker;a5!" 
      -s "Main;/mount;yes;no;no;robinmorajker"
