services:
  samba:
    image: dockurr/samba
    container_name: samba
    restart: unless-stopped

    ports:
      - "139:139"
      - "445:445"

    environment:
      NAME: "RP5"
      USER: "pi"
      PASS: "raspberry"

    volumes:
      - /:/storage

    command: >
      -s "ROOT;/storage;yes;no;yes;all"
