name: cloudflared
services:
    cloudflared:
        command:
            - version
        environment:
            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    	image: wisdomsky/cloudflared-web:latest
        network_mode: host
        ports:
            - target: 443
              published: "443"
              protocol: tcp
        restart: unless-stopped
        x-casaos:
            envs:
                - container: PATH
                  description:
                    en_us: ""
                - container: SSL_CERT_FILE
                  description:
                    en_us: ""
            ports:
                - container: "14333"
                  description:
                    en_us: ""
x-casaos:
    architectures:
        - arm64
    author: CasaOS User
    category: unknown
    description:
        en_us: ""
    developer: unknown
    icon: ""
    main: cloudflared
    port_map: "14333"
    scheme: http
    tagline:
        en_us: This is a compose app converted from a legacy app (CasaOS v0.4.3 or earlier)
    thumbnail: ""
    tips:
        custom: This is a compose app converted from a legacy app (CasaOS v0.4.3 or earlier)
    title:
        en_us: cloudflared
